---
title: "ADS Project 1: Geospatial Analysis of Happiness"
output: html_notebook
---
```{r}
# Loading Data and packages
library(tidyverse)
library(ggplot2)
library(maps)
library(countrycode)

hdb <- read.csv("processed_moments_w_demog.csv")
``` 

# Introduction

[Description of the data project, the variables of analysis, and rationale]

# Geographic Distribution of data set

```{r}
country_count <- table(hdb$country) %>% as.data.frame()

colnames(country_count) <- c("country_code", "freq")

world_map <- map_data("world")

world_map$region <- countrycode(world_map$region, 
                                          "country.name", 
                                          "iso3c")

mapdata <- left_join(world_map, country_count, 
                     by = c("region" = "country_code"))

map1 <- ggplot(mapdata, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = log(freq)), color = "black") + 
  scale_fill_gradient(name = "Moments (Log Scale)",
                      low = "blue", high = "red", 
                      na.value = "grey", 
                      breaks = c(log(10000), log(1000), log(100), log(10)), 
                      labels = c("10000", "1000", "100", "10"))
```
