```{r}
# Loading Data and packages

library(tidyverse)
library(ggplot2)
library(maps)
library(countrycode)
library(tm)
library(topicmodels)
library(flashClust)
library(tidytext)
library(shiny)
library(wordcloud2)
library(DT)

hdb <- read.csv("../output/processed_moments_w_demog.csv")
``` 

```{r}
# Count number of moments by country

country_count <- table(hdb$country) %>% as.data.frame()

colnames(country_count) <- c("country_code", "freq")

# Merge count data with polygon data for map making

world_map <- map_data("world")

world_map$region <- countrycode(world_map$region, 
                                          "country.name", 
                                          "iso3c")

mapdata <- left_join(world_map, country_count, 
                     by = c("region" = "country_code"))

# Create the map using a log scale

map1 <- ggplot(mapdata, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = log(freq)), color = "black") + 
  scale_fill_gradient(name = "Moments (Log Scale)",
                      low = "blue", high = "red", 
                      na.value = "grey", 
                      breaks = c(log(10000), log(1000), log(100), log(10)), 
                      labels = c("10000", "1000", "100", "10"))

ggsave(filename = "Frequency_Map.png", plot = map1, width = 8, height = 4, 
       path = "../figs/")
```

```{r}
# Create DTM object for analysis and save

corpus <- Corpus(VectorSource(hdb$text))

dtm <- DocumentTermMatrix(corpus, 
                          control = list(wordLengths = c(1, Inf)))

# Create TF-IDF for distinctiveness applications

tfidf <- weightTfIdf(dtm)

saveRDS(dtm, "../output/dtm.rds")

saveRDS(dtm,"../output/tfidf.rds")
```

```{r}
# LDA Classification with reasonable number of topics
num_topics <- 5

lda_model <- LDA(dtm, k = num_topics, control = list(seed=356246), 
                 method = "Gibbs") 

# Gibbs sampling for greater distinctiveness between topics

saveRDS(lda_model, "../output/lda_model.rds")

# Plot the top terms

tidy_lda <- tidy(lda_model)

top_terms <- tidy_lda %>%
  group_by(topic) %>%
  slice_max(beta, n = 10) %>% 
  ungroup() %>%
  arrange(topic, -beta)

top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()

ggsave("Top Terms by Topic.png", path = "../figs/")
```

```{r}
# Produce gamma values (topic assignment probabilities) from LDA model

lda_model <- readRDS("../output/lda_model.rds")

gammas <- tidy(lda_model, matrix = "gamma")

gammas_wider <- pivot_wider(gammas, id_cols = document, 
                            names_from = topic,
                            values_from = gamma)

gammas_country <- cbind(gammas_wider, hdb$country)

# Identify topic categories

topic_cats <- c("Shopping", "At Home with Family", 
                "Time with Friends", "Food", "Generic Happiness")

colnames(gammas_country) <- c("document", 
                              paste0("Topic ", c(1:5), 
                                     " ", "(", c(topic_cats), ")"), 
                              "country")

# Average topic gamma values of moments by country

country_avg_gammas <- gammas_country %>%
  group_by(country) %>%
  summarize(
    `Topic 1 (Shopping)` = mean(`Topic 1 (Shopping)`, na.rm = TRUE),
    `Topic 2 (At Home with Family)` = mean(`Topic 2 (At Home with Family)`, 
                                       na.rm = TRUE),
    `Topic 3 (Time with Friends)` = mean(`Topic 3 (Time with Friends)`, 
                                       na.rm = TRUE),
    `Topic 4 (Food)` = mean(`Topic 4 (Food)`, na.rm = TRUE),
    `Topic 5 (Generic Happiness)` = mean(`Topic 5 (Generic Happiness)`, 
                                       na.rm = TRUE))
```


```{r}
# Create maps of topics

topic_map_data <- left_join(world_map, country_avg_gammas, 
                     by = c("region" = "country"))

map_topic_1 <- ggplot(topic_map_data, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = `Topic 1 (Shopping)`), color = "black") + 
  scale_fill_gradient(name = "Shopping Score", 
                      low = "blue", high = "red", 
                       na.value = "grey")

ggsave("Topic 1 Terms Map.png", map_topic_1, path = "../figs/", 
       width = 8, height = 4)

map_topic_2 <- ggplot(topic_map_data, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = `Topic 2 (At Home with Family)`), color = "black") + 
  scale_fill_gradient(name = "At Home with Family Score", 
                      low = "blue", high = "red", 
                       na.value = "grey")

ggsave("Topic 2 Terms Map.png", map_topic_2, path = "../figs/", 
       width = 8, height = 4)

map_topic_3 <- ggplot(topic_map_data, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = `Topic 3 (Time with Friends)`), color = "black") + 
  scale_fill_gradient(name = "Time with Friends Score", 
                      low = "blue", high = "red", 
                       na.value = "grey")

ggsave("Topic 3 Terms Map.png", map_topic_3, path = "../figs/", 
       width = 8, height = 4)

map_topic_4 <- ggplot(topic_map_data, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = `Topic 4 (Food)`), color = "black") + 
  scale_fill_gradient(name = "Food Score", 
                      low = "blue", high = "red", 
                       na.value = "grey")

ggsave("Topic 4 Terms Map.png", map_topic_4, path = "../figs/", 
       width = 8, height = 4)

map_topic_5 <- ggplot(topic_map_data, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = `Topic 5 (Generic Happiness)`), color = "black") + 
  scale_fill_gradient(name = "Generic Happiness Score", 
                      low = "blue", high = "red", 
                       na.value = "grey")

ggsave("Topic 5 Terms Map.png", map_topic_5, path = "../figs/", 
       width = 8, height = 4)
```

```{r}
# Create data frame of average gamma values by country

country_comment_counts <- hdb %>%
  group_by(country) %>%
  summarise(`Comment Count` = n())

count_gamma_df <- left_join(country_avg_gammas, country_comment_counts)

count_gamma_df$country.name <- countrycode(count_gamma_df$country, 
                                           "iso3c", "country.name")

write.csv(count_gamma_df, file = "../output/count_gamma_df.csv", )
```






